/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnalyticsBridge {
    }
}
declare global {
    interface HTMLAnalyticsBridgeElement extends Components.AnalyticsBridge, HTMLStencilElement {
    }
    var HTMLAnalyticsBridgeElement: {
        prototype: HTMLAnalyticsBridgeElement;
        new (): HTMLAnalyticsBridgeElement;
    };
    interface HTMLElementTagNameMap {
        "analytics-bridge": HTMLAnalyticsBridgeElement;
    }
}
declare namespace LocalJSX {
    interface AnalyticsBridge {
    }
    interface IntrinsicElements {
        "analytics-bridge": AnalyticsBridge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "analytics-bridge": LocalJSX.AnalyticsBridge & JSXBase.HTMLAttributes<HTMLAnalyticsBridgeElement>;
        }
    }
}
